/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.java-library-conventions")
}

 repositories {
        // TODO: support enableMavenLocal
        mavenCentral()
    }
dependencies {
    api("jakarta.xml.bind:jakarta.xml.bind-api:4.0.1")
     implementation("org.mozilla:rhino:1.7.14")
    implementation("commons-codec:commons-codec:1.16.0")
    implementation("org.apache.commons:commons-jexl:2.1")
    implementation("org.apache.commons:commons-jexl3:3.2.1")
    implementation("org.apache.commons:commons-lang3:3.14.0") {
        because("StringUtils")
    }
    implementation("commons-io:commons-io:2.15.1") {
        because("FileUtils")
    }
}
