/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.java-library-conventions")
}

repositories {
        // TODO: support enableMavenLocal
        mavenCentral()
    }
dependencies {
    
    api("org.mongodb:mongo-java-driver:3.12.14")
    implementation("org.apache.commons:commons-lang3:3.14.0") {
        because("StringUtils")
    }
    implementation("org.apache.commons:commons-dbcp2:2.11.0")
    
    implementation("commons-io:commons-io:2.15.1") {
        because("IOUtils")
    }
}
