/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.java-library-conventions")
}

repositories {
        // TODO: support enableMavenLocal
        mavenCentral()
    }
dependencies {
    api("org.slf4j:slf4j-api:2.0.9")

    implementation("commons-io:commons-io:2.15.0")
    implementation("org.apache.commons:commons-collections4:4.4")
    implementation("org.apache.commons:commons-lang3:3.14.0")
    implementation("org.apache.commons:commons-math3:3.6.1")
    implementation("org.apache.commons:commons-text:1.11.0")
}
