

    /*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.java-library-conventions")
}

repositories {
        // TODO: support enableMavenLocal
        mavenCentral()
    }
dependencies {
    
    api("org.apache.logging.log4j:log4j-api:2.22.0")
    api("org.apache.logging.log4j:log4j-core:2.22.0") {
        because("GuiLogEventAppender is using log4j-core to implement GUI-based log appender")
    }
    api("org.apache.logging.log4j:log4j-slf4j2-impl:2.22.0") {
        because("Both log4j and slf4j are included, so it makes sense to just add log4j->slf4j bridge as well")
    }
    api("org.apiguardian:apiguardian-api:1.1.2")
    api("oro:oro:2.0.8") {
        because("Perl5Matcher org.apache.jmeter.util.JMeterUtils.getMatcher()")
    }
}
