/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.java-library-conventions")

}

repositories {
        // TODO: support enableMavenLocal
        mavenCentral()
    }
dependencies {
    
    api("javax.mail:mail:1.4.7") {
        exclude("javax.activation", "activation")
    }
    // There's no javax.activation:activation:1.2.0, so we use com.sun...
    runtimeOnly("com.sun.activation:javax.activation:1.1.1")
    // This is an API-only jar. javax.activation is present in Java 8,
    // however it is not there in Java 9
    compileOnly("javax.activation:javax.activation-api:1.2.0")
    implementation("org.apache.commons:commons-lang3:3.14.0") {
        because("StringUtils")
    }
}
