/*
 * This file was generated by the Gradle 'init' task.
 */

plugins {
    id("demo.java-library-conventions")
}

repositories {
        // TODO: support enableMavenLocal
        mavenCentral()
    }
dependencies {
    
        api("bsf:bsf:2.4.0")
        api("cglib:cglib-nodep:3.3.0")
        api("com.fasterxml.jackson.core:jackson-annotations:2.15.2")
        api("com.fasterxml.jackson.core:jackson-core:2.15.2")
        api("com.fasterxml.jackson.core:jackson-databind:2.15.2")
        api("com.fifesoft:rsyntaxtextarea:3.3.4")
        api("com.formdev:svgSalamander:1.1.4")
        api("com.github.ben-manes.caffeine:caffeine:2.9.3")
        api("com.github.weisj:darklaf-core:2.7.3")
        api("com.github.weisj:darklaf-extensions-rsyntaxarea:0.3.4")
        api("com.github.weisj:darklaf-property-loader:2.7.3")
        api("com.github.weisj:darklaf-theme:2.7.3")
        api("com.google.auto.service:auto-service-annotations:1.1.1")
        api("com.google.auto.service:auto-service:1.1.1")
        api("com.google.errorprone:error_prone_annotations:2.23.0")
        api("com.helger.commons:ph-commons:10.2.5")
        api("com.helger:ph-css:6.5.0")
        api("com.jayway.jsonpath:json-path:2.8.0")
        api("com.miglayout:miglayout-core:5.3")
        api("com.miglayout:miglayout-swing:5.3")
        api("com.sun.activation:javax.activation:1.2.0")
        api("com.thoughtworks.xstream:xstream:1.4.20")
        api("commons-codec:commons-codec:1.16.0")
        api("commons-collections:commons-collections:3.2.2")
        api("commons-io:commons-io:2.15.1")
        api("commons-lang:commons-lang:2.6")
        api("commons-logging:commons-logging:1.2")
        api("commons-net:commons-net:3.10.0")
        api("dnsjava:dnsjava:2.1.9")
        api("io.burt:jmespath-core:0.6.0")
        api("io.burt:jmespath-jackson:0.6.0")
        api("javax.activation:javax.activation-api:1.2.0")
        api("javax.mail:mail:1.5.0-b01")
        api("jcharts:jcharts:0.7.5")
        
}
